# docker-compose.yml
version: "3.5"
services:
  studio:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/home/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
    entrypoint: []
    command: tail -f /dev/null  # Keep the container running indefinitely
    # command:  /bin/bash -c "chmod +x /home/plutus/workspace/.devcontainer/scripts/on-create-container.sh && /home/plutus/workspace/.devcontainer/scripts/on-create-container.sh && while sleep 1000; do :; done"
    extra_hosts:
      - "host.docker.internal:host-gateway"
